#!/bin/bash

int1=0    #Define global variables
int2=0

inputs() {
    read -p "Enter two integers: " int1 int2   #Read two parameters from standard input
}

exitPrompt(){
    read -p "Do you wish to continue? [y]es or [n]o: " ans
    if [ $ans == 'n' ]
    then
        echo "Exiting the script. Have a nice day!"
        return 1  #return value
    else
        return 0
    fi
}

while (true)
do
    clear
    printf "Choose from the following operations: \n"
    printf "[a]Addition [b]Subtraction [c] Multiplication [d]Division\n"
    read -p "### Your choice: " choice
    case $choice in
        [aA])
            inputs
            res=$((int1+int2))
            ;;
        [bB])
            inputs
            res=$((int1-int2))
            ;;
        [cC])
            inputs
            res=$((int1*int2))
            ;;
        [dD])
            inputs
            res=$((int1/int2))
            ;;
        *)
            res=0
            echo "wrong choice!"
    esac
    echo "The result is: " $res
    exitPrompt
    res=$?          #Gets the return value of the last function execution
    if [ $res -eq 1 ]; then
        break
    fi
done
